"""
Django settings for cas project.

Generated by 'django-admin startproject' using Django 1.10.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SECRET_KEY = 'w#=zy6j63s4i-98hjc)o7l+84xjo9a$cpef6li-45$uf!2y@70'

ALLOWED_HOSTS = ['*']

INSTALLED_APPS = ['auth']

MIDDLEWARE = [
    'django.middleware.common.CommonMiddleware',
    'cas.middleware.ErrorHandlingMiddleware',
]

LOGGING = {
    'version': 1,
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler'
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console']
        },
        'cas': {
            'handlers': ['console'],
            'propagate': True,
        },
        'auth': {
            'handlers': ['console'],
            'propagate': True,
        },
    },
}

ROOT_URLCONF = 'cas.urls'

WSGI_APPLICATION = 'cas.wsgi.application'

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = False

USE_L10N = False

USE_TZ = False

DEBUT = True
